services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: hyperv_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - hypervnet

  api:
    container_name: hyperv_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${DB_PORT}/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${API_PORT}
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - postgres
    networks:
      - hypervnet
    command: npm run dev

volumes:
  postgres-data:

networks:
  hypervnet:
    driver: bridge
